# Generated by Django 5.1.2 on 2024-10-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connectivity',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='device',
            name='operating_system',
            field=models.CharField(max_length=35),
        ),
    ]
