# Generated by Django 5.1.2 on 2024-10-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_device_connectivity_alter_device_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='battery',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='colors',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='device',
            name='connectivity',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='dimensions',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='device',
            name='operating_system',
            field=models.CharField(max_length=27),
        ),
        migrations.AlterField(
            model_name='device',
            name='weight',
            field=models.CharField(max_length=25),
        ),
    ]
